### PR TITLE
[docs]:Added Issue Template

### LINKED ISSUE #27: Issue Template is missing from this project.
Hi @colbyfayock ,

I was just going through this project  and saw Issue Template is missing, as per [Github Community Standards recommendations](https://github.com/colbyfayock/next-cloudinary/community) that would make the project contributor friendly.

Let me know if this is something you would allow me to implement under Hacktoberfest.

### PR DESCRIPTION
**Pull request by Kunal-8789**
Added the recommended Issue Template to make the project contributor friendly.
fixes #27

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @Kunal-8789 can you add everything else from that PR pelase?

also please update the descrip

**Comment by Kunal-8789** [comment]
hey @colbyfayock ,Please review the changes.

**Comment by colbyfayock** [comment]
@Kunal-8789 can you please update the template to use links for this repository? there are a few that still point to https://github.com/colbyfayock/next-cloudinary

**Comment by Kunal-8789** [comment]
@colbyfayock I have updated the template. Please Review.

**Comment by colbyfayock** [comment]
looks good, thanks

please email me at hello@colbyfayock.com where i'll send you a form to claim your free Hacktoberfest swag 

https://spacejelly.dev/hacktoberfest/

**Comment by colbyfayock** [comment]
@all-contributors please add @Kunal-8789 for tool

**Pull request merged**
