### PR TITLE
Improved_readme.md

### PR DESCRIPTION
**Pull request by Abubakrce19**
# Description

## Issue Ticket Number

Fixes 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have created an [issue](https://github.com/colbyfayock/netlify-plugin-cloudinary/issues) ticket for this PR
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/netlify-plugin-cloudinary/pulls) for the same update/change?
- [ ] I have performed a self-review of my own code
- [ ] I have run tests locally to ensure they all pass
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by Abubakrce19** [comment]
[Visit the deploys page to approve it](https://app.netlify.com/sites/netlify-plugin-cloudinary/deploys)
what do this means??

**Comment by colbyfayock** [comment]
thanks @Abubakrce19

**Comment by colbyfayock** [comment]
@all-contributors please add @Abubakrce19 for doc

**Comment by colbyfayock** [comment]
Email me at hello@colbyfayock.com to claim your hacktoberfest swag https://spacejelly.dev/hacktoberfest/

**Pull request merged**
